name: shop_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
        - asset: lib/assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: lib/assets/fonts/Anton-Regular.ttf

